---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: $APP_NAME
  namespace: staging
spec:
  minReplicas: 2
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: $APP_NAME
  targetCPUUtilizationPercentage: 50
