export enum Permission {
  ATTRACTION_CREATE = 'attraction_create',
  ATTRACTION_UPDATE = 'attraction_update',
  ATTRACTION_DELETE = 'attraction_delete',
  ATTRACTION_READ = 'attraction_read',
  RESTAURANT_CREATE = 'restaurant_create',
  RESTAURANT_UPDATE = 'restaurant_update',
  RESTAURANT_DELETE = 'restaurant_delete',
  RESTAURANT_READ = 'restaurant_read',
  USER_CREATE = 'user_create',
  USER_UPDATE = 'user_update',
  USER_DELETE = 'user_delete',
  USER_READ = 'user_read',
  PERMISSION_GROUP_CREATE = 'permissionGroup_create',
  PERMISSION_GROUP_UPDATE = 'permissionGroup_update',
  PERMISSION_GROUP_DELETE = 'permissionGroup_delete',
  PERMISSION_GROUP_READ = 'permissionGroup_read',
  REVIEW_CREATE = 'review_create',
  REVIEW_UPDATE = 'review_update',
  REVIEW_DELETE = 'review_delete',
  REVIEW_READ = 'review_read',
}
